### ISSUE TITLE
Terraform commands undefined in Go script run in CircleCI

### ISSUE THREAD

**Issue by marceluniper** [gruntwork-io/terratest#1032]
I am trying to get Terratest to work in CircleCI and face the following problem: 
![image](https://user-images.githubusercontent.com/91940524/142439417-1fcc9bc2-8e14-409f-8a9e-c9cf2e501b6a.png)
end2end_test.go looks as follows
```
package test

import (
	"testing"

	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/assert"
)

func TestTerraformHelloWorldExample(t *testing.T) {
	
	// Construct the terraform options with default retryable errors to handle the most common
	// retryable errors in terraform testing.
	terraformOptions := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
		// Set the path to the Terraform code that will be tested.
		TerraformDir: "../",
	})

	// Clean up resources with "terraform destroy" at the end of the test.
	defer terraform.Destroy(t, terraformOptions)

	// Run "terraform init" and "terraform apply". Fail the test if there are any errors.
	terraform.InitAndApply(t, terraformOptions)

	// Run `terraform output` to get the values of output variables and check they have the expected values.
	output := terraform.Output(t, terraformOptions, "hello_world")
	assert.Equal(t, "Hello, World!", output)
}
```
and my config.yml like this:
```
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    # only build the circleci branch for now
    docker:
      # specify the version
      - image: circleci/golang:1.14
      - image: hashicorp/terraform
    working_directory: /go/src/terratest_poc
    steps:
      - checkout
      - run: ls && pwd
      - run: cd test && go get -v -d -t
      - run: cd test && go test -v -timeout 30m 
```
I am wondering why `terraform.WithDefaultRetryableErrors` is apparently undefined although I imported `github.com/gruntwork-io/terratest/modules/terraform`.

**Comment by yorinasub17** [comment]
I would double check the version of terratest that is defined in your `go.mod` file or checked out in your `vendor` folder. You are most likely pulling in an older version of terratest that doesn't include that function.

**Comment by marceluniper** [comment]
> I would double check the version of terratest that is defined in your `go.mod` file or checked out in your `vendor` folder. You are most likely pulling in an older version of terratest that doesn't include that function.

Thanks a lot! This solved the issue! Do you also know how to fix the issue that terraform executable is not found, although I installed the Docker image?
![image](https://user-images.githubusercontent.com/91940524/142447624-96610846-851d-4d34-9b22-5856b0b090fc.png)

**Comment by yorinasub17** [comment]
Multiple images in circleci don't stack together, and it works more like `docker-compose`. The jobs run only in the first container (in your case, `circleci/golang:1.14`). See [this post](https://discuss.circleci.com/t/please-explain-multiple-images-in-an-executor/36572) for more details on how multiple images work.

So what you need to do is either:

- Create a docker image that contains both golang and terraform
- Install terraform explicitly into the `circleci/golang` image.

You should be able to do the latter with the following snippet in your job steps:

```
steps:
  - checkout
  - run:
      name: install terraform
      command: |
        mkdir -p ~/terraform
        wget https://releases.hashicorp.com/terraform/${version}/terraform_${version}_linux_amd64.zip
        unzip -o terraform_${version}_linux_amd64.zip -d ~/terraform
        chmod u+x ~/terraform/terraform*
        mv ~/terraform/terraform* /usr/local/bin
  - # other run steps
```

**Comment by yorinasub17** [comment]
Ah you can also use the CircleCI orb [for terraform](https://github.com/CircleCI-Public/terraform-orb).

**Comment by marceluniper** [comment]
> Ah you can also use the CircleCI orb [for terraform](https://github.com/CircleCI-Public/terraform-orb). Note that for this, all you need is the `terraform/install` step.

Thank you! For future reference, here is my config.yml which now works flawlessly:
```
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0
  
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14
    working_directory: /go/src/terratest_poc
    steps:
      - checkout
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 0.14.2
      - run: cd test && go get -v -d -t
      - run: cd test && go test -v -timeout 30m 
```
