### ISSUE TITLE
Error PodNotAvailable not handled in proper way

### ISSUE THREAD

**Issue by shmykyta** [gruntwork-io/terratest#1326]
**Describe the bug**

In our test using function `WaitUntilPodAvailableE` and when we updated the library we that that enhancement what should clarify the issue why pod is failing or not ready is always return `,` and `.` in reason and message.

Current log: 

```
Wait for pod sleeper to be provisioned. returned an error: Pod sleeper is not available, reason: , message: . Sleeping for 5s and will try again.
```

**To Reproduce**

Kuberenetes cluster version: 1.24
Lib version: v0.43.0

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sleeper
  labels:
    app: sleeper
spec:
  containers:
    - name: sleeper
      image: ubuntu
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - !
            - sleep 100
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
      command: [ "/bin/sh" ]
      args: [ "-c", "sleep 300" ]
```

```go
k8s.WaitUntilPodAvailableE(t, options, podName, count, 5*time.Second)
```

**Expected behavior**

Proper error reason and message

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terratest version: v0.43.0
- Kubernetes version: 1.24
- Go version: 1.19

**Additional informantin** 

PR with changes: https://github.com/gruntwork-io/terratest/pull/1223
