### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by JCzz** [gruntwork-io/terratest#1403]
**Describe the bug**
I was expecting terratest to use client-go, when run in container within a container?

**To Reproduce**
Create a Dockerfile:
```
# syntax=docker/dockerfile:1

FROM golang:1.21.7 AS builder
ARG TEST_FOLDER

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY $TEST_FOLDER/*.go ./
COPY $TEST_FOLDER/*.yml ./
```

Build using:
```
TEST_FOLDER=./kubernetes-hello-world-example
DOCKERFILE=./Dockerfile
docker build --build-arg="TEST_FOLDER=$TEST_FOLDER" --target builder -t terratest:latest -q -f Dockerfile .
```

Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: docker.io/library/terratest:latest
    imagePullPolicy: Never
    command: ["go"]
    args: ["test", "kubernetes_hello_world_example_test.go"]
  restartPolicy: OnFailure
```
## Error:

```go
kubernetes_hello_world_example_test.go:25
                Error:          Received unexpected error:
                                error while running command: exec: "kubectl": executable file not found in $PATH; 
```

**Expected behavior**

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terratest version:
- Environment details (Ubuntu 20.04, Windows 10, etc.):

**Additional context**
